<a href="https://colab.research.google.com/github/madixson/EmployeeChurnHR_Project/blob/main/Models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Connect Notebook to Google Drive
For file accessing

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


## Import Necessary Libraries

In [14]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

# KNN
from sklearn.neighbors import KNeighborsClassifier

# RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.tree import plot_tree

# Bayes
from sklearn.naive_bayes import GaussianNB

# Logistic Regression
from sklearn.linear_model import LogisticRegression

# NN
from keras.models import Sequential
from keras.layers import Dense

## Load Data
**Note: Edit the correct file pathing to your datasets

In [3]:
# Load in CSV dataset
df = pd.read_csv('/content/drive/MyDrive/EmployeeChurnProject/NewEmployeeData.csv')
target = pd.read_csv('/content/drive/MyDrive/EmployeeChurnProject/target_col.csv')

## Model Settings

In [10]:
# Label predictive variable and remove from dataset & convert to np array
y = np.array(target)  # Convert target variable to numpy array
X = np.array(df)  # Convert features to numpy array
feature_list = list(df.columns)

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

# Standardize features by removing the mean and scaling to unit variance
scaler = StandardScaler()  
scaler.fit(X_train)  # Fit the scaler to the training data
X_train = scaler.transform(X_train)  # Scale the training data
X_test = scaler.transform(X_test)  # Scale the test data using the same scaler as the training data

## Models

### KNN

In [15]:
# Instantiate KNeighborsClassifier object
knn = KNeighborsClassifier(n_neighbors = 2, metric = 'euclidean')

# Train the model on the training set
knn.fit(X_train, y_train)

# Predict the target variable on the test set
y_pred = knn.predict(X_test)

# Print results
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


[[3417    0]
 [   2 1081]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3417
           1       1.00      1.00      1.00      1083

    accuracy                           1.00      4500
   macro avg       1.00      1.00      1.00      4500
weighted avg       1.00      1.00      1.00      4500



### Random Forest

In [16]:
# Random forest model creation
rfc = RandomForestClassifier()
rfc.fit(X_train, y_train)

# Predictions
rfc_predict = rfc.predict(X_test)
rfc_cv_score = cross_val_score(rfc, X, y, cv=10, scoring='roc_auc')

# Print Results
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

<ipython-input-16-cc7e5572b8f6>:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rfc.fit(X_train, y_train)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples

[[3417    0]
 [   2 1081]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3417
           1       1.00      1.00      1.00      1083

    accuracy                           1.00      4500
   macro avg       1.00      1.00      1.00      4500
weighted avg       1.00      1.00      1.00      4500



### Naive Bayes

In [17]:
# Naive Bayes model creation
GNB = GaussianNB()
GNB.fit(X_train, y_train)

# Predict the target variable on the test set
y_pred = GNB.predict(X_test)

# Print results
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[3417    0]
 [   0 1083]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3417
           1       1.00      1.00      1.00      1083

    accuracy                           1.00      4500
   macro avg       1.00      1.00      1.00      4500
weighted avg       1.00      1.00      1.00      4500



/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


### Logistic Regression

In [18]:
# logistic regression model creation
lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)

# predictions
lr_predict = lr.predict(X_test)

# evaluation
print(confusion_matrix(y_test, lr_predict))
print(classification_report(y_test, lr_predict))

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[3417    0]
 [   0 1083]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3417
           1       1.00      1.00      1.00      1083

    accuracy                           1.00      4500
   macro avg       1.00      1.00      1.00      4500
weighted avg       1.00      1.00      1.00      4500



### MLP Neural Network

In [19]:
# neural network model creation
nn = Sequential()
nn.add(Dense(64, input_dim=X_train.shape[1], activation='relu'))
nn.add(Dense(32, activation='relu'))
nn.add(Dense(1, activation='sigmoid'))

nn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# training
nn.fit(X_train, y_train, epochs=50, batch_size=32, verbose=0)

# predictions
nn_prob = nn.predict(X_test)
nn_predict = (nn_prob > 0.5).astype(int)

# evaluation
print(confusion_matrix(y_test, nn_predict))
print(classification_report(y_test, nn_predict))

141/141 [==============================] - 0s 2ms/step
[[3417    0]
 [   0 1083]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3417
           1       1.00      1.00      1.00      1083

    accuracy                           1.00      4500
   macro avg       1.00      1.00      1.00      4500
weighted avg       1.00      1.00      1.00      4500

